# Generated by Django 5.1.5 on 2025-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYS_ADMIN', 'System Administrator'), ('INVESTOR', 'Investor'), ('AGENT', 'Agent'), ('PROMOTER', 'Promoter')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
