# Generated by Django 5.1.5 on 2025-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_created_date_alter_role_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('SYS_ADMIN', 'System Administrator'), ('INVESTOR', 'Investor'), ('AGENT', 'Agent'), ('PROMOTER', 'Promoter')], max_length=50, unique=True),
        ),
    ]
