# Generated by Django 5.1.5 on 2025-03-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duser', '0001_initial'),
        ('organization', '0002_alter_organization_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duser.duser')),
            ],
            options={
                'db_table': 'user_organizations',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
