# Generated by Django 5.1.5 on 2025-03-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_created_date_and_more'),
        ('property', '0002_alter_property_created_date_alter_property_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='organization.organization'),
        ),
    ]
