# Generated by Django 5.1.5 on 2025-03-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_created_date_and_more'),
        ('property', '0003_property_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='organization.organization'),
        ),
    ]
