# Generated by Django 5.1.5 on 2025-03-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='organization',
        ),
    ]
