# Generated by Django 5.1.5 on 2025-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default=1111, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
