# Generated by Django 5.1.5 on 2025-03-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_email_and_more'),
        ('property', '0006_property_postal_code_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='organization.organization'),
            preserve_default=False,
        ),
    ]
