# Generated by Django 5.1.5 on 2025-03-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Terreno', 'Terreno'), ('Casa', 'Casa'), ('Loja', 'Loja'), ('Armazém', 'Armazém'), ('Escritório', 'Escritório'), ('Quinta', 'Quinta'), ('Prédio', 'Prédio'), ('Garagem', 'Garagem'), ('Outro', 'Outro')], max_length=255),
        ),
    ]
