# Generated by Django 5.1.5 on 2025-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='last_modified_date',
        ),
        migrations.AddField(
            model_name='property',
            name='area_bruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='area_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='certificado_energetico',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('E', 'E'), ('D', 'D'), ('C', 'C'), ('B-', 'B-'), ('B', 'B'), ('A', 'A'), ('A+', 'A+')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='imagens',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='informacoes_adicionais',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nova_construcao',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='numero_casas_banho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='preco_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='preco_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tipologia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
