# Generated by Django 5.1.5 on 2025-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_remove_property_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='numero_casas_banho',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='tipologia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
