# Generated by Django 5.1.5 on 2025-06-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area_util',
            new_name='net_area',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='numero_casas_banho',
            new_name='num_wc',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='tipologia',
            new_name='typology',
        ),
    ]
