# Generated by Django 5.1.5 on 2025-06-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_rename_area_util_property_net_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='certificado_energetico',
            new_name='energy_certf',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='area_bruta',
            new_name='gross_area',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='preco_maximo',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='preco_minimo',
            new_name='min_price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='nova_construcao',
            new_name='new_construction',
        ),
    ]
