# Generated by Django 5.1.5 on 2025-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
    ]
