# Generated by Django 5.1.5 on 2025-04-07 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_property_type'),
        ('property_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymedia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertymedia',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='propertymedia',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='propertymedia',
            name='last_modified_date',
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='property_media/'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='property.property'),
        ),
    ]
