# Generated by Django 5.1.5 on 2025-04-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_roi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROICalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repair_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('after_repair_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('holding_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('roi_result', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roi_calculations',
            },
        ),
        migrations.DeleteModel(
            name='PropertyRoi',
        ),
    ]
