# Generated by Django 5.1.5 on 2025-03-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_created_date_and_more'),
        ('property', '0005_remove_property_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', unique=True),
        ),
    ]
