# Generated by Django 5.1.5 on 2025-04-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_expiry_date_announcement_price'),
        ('property', '0009_remove_property_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
