# Generated by Django 5.1.5 on 2025-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_vat_number_organization_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
