# Generated by Django 5.1.5 on 2025-03-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('user', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organization',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.role'),
        ),
    ]
