# Generated by Django 5.1.5 on 2025-03-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_organization_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('DONT_WANT_TO_SAY', "Don't want to say")], max_length=18)),
                ('lang_key', models.CharField(choices=[('PT', 'Portuguese'), ('ENG', 'English')], max_length=10)),
                ('activated', models.BooleanField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'd_user',
            },
        ),
    ]
