# Generated by Django 5.1.5 on 2025-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0001_initial'),
        ('organization', '0002_alter_organization_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duser',
            name='institution',
        ),
        migrations.AddField(
            model_name='duser',
            name='institutions',
            field=models.ManyToManyField(related_name='users', to='organization.organization'),
        ),
    ]
