# Generated by Django 5.1.5 on 2025-03-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0002_remove_duser_institution_duser_institutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duser',
            old_name='institutions',
            new_name='institution',
        ),
    ]
