# Generated by Django 5.1.5 on 2025-03-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0003_rename_institutions_duser_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duser',
            name='gender',
        ),
    ]
