# Generated by Django 5.1.5 on 2025-04-16 17:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0004_remove_duser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='PT'),
        ),
    ]
