# Generated by Django 5.1.5 on 2025-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0004_remove_duser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
