# Generated by Django 5.1.5 on 2025-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0005_duser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
