# Generated by Django 5.1.5 on 2025-04-16 18:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0005_duser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+351912345678', max_length=128, region='PT'),
            preserve_default=False,
        ),
    ]
