# Generated by Django 5.1.5 on 2025-04-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0006_alter_duser_email'),
        ('duser', '0006_alter_duser_phone_number'),
    ]

    operations = [
    ]
