# Generated by Django 5.1.5 on 2025-05-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('duser', '0008_remove_duser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duser',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='duser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='duser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='duser',
            name='password',
            field=models.CharField(default='IMOINVESTOR', max_length=255),
        ),
        migrations.AddField(
            model_name='duser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
