# Generated by Django 5.1.5 on 2025-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0009_remove_duser_password_hash_duser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='duser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='duser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='duser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
