# Generated by Django 5.1.5 on 2025-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0010_remove_duser_groups_remove_duser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
