# Generated by Django 5.1.5 on 2025-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0011_duser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='created_by',
            field=models.CharField(default='system', max_length=255),
        ),
    ]
