# Generated by Django 5.1.5 on 2025-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_announcement_is_active'),
        ('duser', '0012_alter_duser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='announcements.announcement'),
        ),
    ]
