# Generated by Django 5.1.5 on 2025-06-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0013_duser_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duser',
            name='favourites',
        ),
    ]
