# Generated by Django 5.1.5 on 2025-06-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duser', '0016_duser_payment_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duser',
            name='payment_token',
        ),
    ]
